config/routes.rb
Rails.application.routes.draw do
  resources :shorteners
  root 'shorteners#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortener.rb
class Shortener < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shorteners_controller.rb
class ShortenersController < ApplicationController
  before_action :set_shortener, only: [:show, :edit, :update, :destroy]

  # GET /shorteners
  # GET /shorteners.json
  def index
    @shorteners = Shortener.all
  end

  # GET /shorteners/1
  # GET /shorteners/1.json
  def show
    @shortener = Shortener.find(params[:id])
    redirect_to @shortener.original_url
  end

  # GET /shorteners/new
  def new
    @shortener = Shortener.new
  end

  # GET /shorteners/1/edit
  def edit
  end

  # POST /shorteners
  # POST /shorteners.json
  def create
    @shortener = Shortener.new(shortener_params)

    respond_to do |format|
      if @shortener.save
        format.html { redirect_to shorteners_path, notice: 'Shortener was successfully created.' }
        format.json { render :show, status: :created, location: @shortener }
      else
        format.html { render :new }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorteners/1
  # PATCH/PUT /shorteners/1.json
  def update
    respond_to do |format|
      if @shortener.update(shortener_params)
        format.html { redirect_to @shortener, notice: 'Shortener was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortener }
      else
        format.html { render :edit }
        format.json { render json: @shortener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorteners/1
  # DELETE /shorteners/1.json
  def destroy
    @shortener.destroy
    respond_to do |format|
      format.html { redirect_to shorteners_url, notice: 'Shortener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortener
      @shortener = Shortener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortener_params
      params.require(:shortener).permit(:original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorteners_helper.rb
module ShortenersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorty yo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shorteners/_form.html.erb
<%= form_with(model: shortener, local: true) do |form| %>
  <% if shortener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortener.errors.count, "error") %> prohibited this shortener from being saved:</h2>

      <ul>
      <% shortener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

Origianl "Long" URL: <%= form.text_field :original_url, id: :shortener_original_url %> <br><br>


  <div class="actions">
    <%= form.submit %>
  </div> <br>
<% end %>

app/views/shorteners/edit.html.erb
<h1>Editing Shortener</h1>

<%= render 'form', shortener: @shortener %>

<%= link_to 'Show', @shortener %> |
<%= link_to 'Back', shorteners_path %>

app/views/shorteners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shortenizle</h1>

<table>
  <thead>
    <tr>
      <th>Original url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shorteners.each do |shortener| %>
      <tr>
        <td><%= shortener.original_url %></td>
        <td><%= link_to "Go To URL", shortener %></td>
        <td><%= link_to 'Edit', edit_shortener_path(shortener) %></td>
        <td><%= link_to 'Destroy', shortener, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortener', new_shortener_path %>

app/views/shorteners/new.html.erb
<h1>New Shorty</h1>

<%= render 'form', shortener: @shortener %>

<%= link_to 'Back', shorteners_path %>

app/views/shorteners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original url:</strong>
  <%= @shortener.original_url %>
</p>

<%= link_to 'Edit', edit_shortener_path(@shortener) %> |
<%= link_to 'Back', shorteners_path %>